# Generated by Django 4.1.5 on 2023-01-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serpo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='reddy', upload_to='Gallary'),
            preserve_default=False,
        ),
    ]
